language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps


matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            cmake

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install cmake -y
script:
  - make
  - build/main
  - make clean
