language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5
      env:
         - CC_VER=5
         - CMAKE_CXX_FLAGS="-std=c++11"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-6
      env:
        - CC_VER=6

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
      env:
        - CC_VER=7

script:
  - mkdir build
  - cd build
  - export CC=gcc-$CC_VER
  - export CXX=g++-$CC_VER
  - $CXX --version
  - cmake ..
  - make
  - demo1_c < echo "\n"
  - demo1_cpp < echo "\n"
